# Generated by Django 2.2.1 on 2019-05-30 11:57

import django.core.validators
from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190530_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(0), main.validators.validate_even_number]),
        ),
    ]
